### ISSUE TITLE
Action overwrites existing release description

### ISSUE THREAD

**Issue by kdewald** [djnicholson/release-action#1]
Whenever this action runs, it is currently overwriting the description of the existing release with the following text:

`Updated on Fri Jul 17 2020 02:07:32 GMT+0000 (Greenwich Mean Time) by GitHub action: "djnicholsonrelease-action4"`

Is there a way this behavior can be modified or removed?

Thanks!

**Comment by djnicholson** [comment]
Right now it is not customizable, but that could change.

What are your requirements? To specify a string to use within the action config? Or to have it not change whatever description the release already has?

Feel free to submit a PR if you want to make the change yourself.  This is the file that will need editing: https://github.com/djnicholson/release-action/blob/master/src/index.ts

**Comment by kdewald** [comment]
Ideally it would be better if the description wasn't modified at all. I would just append that string in the case of a new release being made.

I'm not familiar with the Github API, but I'll try to submit a PR. (If you can point me in the right direction to speed up my search I"ll appreciate it :-) )

**Comment by djnicholson** [comment]
Sorry for the slow fix @kdewald 

As of djnicholson/release-action@v2.7 the description is not overwritten.
